### ISSUE TITLE
Error when user not logged in

### ISSUE THREAD

**Issue by cakebread** [tedivm/tedivms-flask#11]
Accessing the site when not logged in throws this error:

app_1       | Traceback (most recent call last):
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
app_1       |     return self.wsgi_app(environ, start_response)
app_1       |   File "/usr/local/lib/python3.7/site-packages/beaker/middleware.py", line 156, in __call__
app_1       |     return self.wrap_app(environ, session_start_response)
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
app_1       |     response = self.handle_exception(e)
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
app_1       |     reraise(exc_type, exc_value, tb)
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
app_1       |     raise value
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
app_1       |     response = self.full_dispatch_request()
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
app_1       |     rv = self.handle_user_exception(e)
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1816, in handle_user_exception
app_1       |     return self.handle_http_exception(e)
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1744, in handle_http_exception
app_1       |     return handler(e)
app_1       |   File "./app/__init__.py", line 286, in error_pagenotfound
app_1       |     return show_error(404, 'Page not found.')
app_1       |   File "./app/__init__.py", line 274, in show_error
app_1       |     return render_template('pages/errors.html', error_code=status, message=message), status
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
app_1       |     ctx.app,
app_1       |   File "/usr/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
app_1       |     rv = template.render(context)
app_1       |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
app_1       |     self.environment.handle_exception()
app_1       |   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
app_1       |     reraise(*rewrite_traceback_stack(source=source))
app_1       |   File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
app_1       |     raise value.with_traceback(tb)
app_1       |   File "/app/app/templates/pages/errors.html", line 1, in top-level template code
app_1       |     {% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}
app_1       |   File "/app/app/templates/common/dark_base.html", line 1, in top-level template code
app_1       |     {% extends "dark_layout.html" %}
app_1       |   File "/app/app/templates/dark_layout.html", line 33, in top-level template code
app_1       |     {% block body %}
app_1       |   File "/app/app/templates/dark_layout.html", line 67, in block "body"
app_1       |     {% if current_user.has_role('admin') or current_user.has_role('dev') %}
app_1       | jinja2.exceptions.UndefinedError: 'flask_login.mixins.AnonymousUserMixin object' has no attribute 'has_role'

**Comment by cakebread** [comment]
This works for me, not sure if it's the correct way:

+                     {% if current_user.is_authenticated %}
                       {% if current_user.has_role('admin') or current_user.has_role('dev') %}

+                 {% if current_user.is_authenticated %}
                         {% if current_user.has_role('admin') %}

**Comment by tedivm** [comment]
Thanks for the PR!
