### ISSUE TITLE
Celery worker exited.

### ISSUE THREAD

**Issue by tishacian** [tedivm/tedivms-flask#5]
Hi,

Thanks for this project, it seems to be a really great boilerplate.
Just one question : when I make testenv, during the launching of the network, I encounter an issue with the Celery worker.

```
worker_1    | Launching celery worker with beat enabled
worker_1    | celery worker -A app.worker:celery --loglevel=info --autoscale=10,2 -B -s /home/apprunner/celerybeat-schedule
worker_1    | Error:
worker_1    | Unable to load celery application.
worker_1    | The module app.tasks was not found.
worker_1    |
my_app_worker_1 exited with code 1
```

I use Docker v 19.03.2, and I don't get why the app.tasks module is not found. Is it an issue with rabbitmq-server?
Any help would be really appreciate.

**Comment by tedivm** [comment]
This is resolved with the latest commit. The issue was there was an import that didn't exist in the project anymore.

It's important to note that if you do want to use the celery worker you'll need to import all of your celery tasks into that worker.py file.
