### ISSUE TITLE
Fix for ImportError: cannot import name 'url_encode' from 'werkzeug'

### ISSUE THREAD

**Issue by BackSeat** [tedivm/tedivms-flask#7]
`make init-db` fails with above.

Reason: flask_wtf v0.14.2 says, `from werkzeug import url_encode`.  Werkzeug changed the url_encode function from `werkzeug.url_encode` to `werkzeug.urls.url_encode`

Fix: update requirements.txt to `Flask-WTF==0.14.3`

Caveat: I haven't checked whether there are other incompatibilities introduced by bumping Flask-WTF (although it seems unlikely).

**Comment by tedivm** [comment]
Thanks for reporting!
